package randomdatagenerator;

import java.util.Random;

public class RandomDataGenerator {

    private Random rng = new Random();

    public String getPersonName() {
        StringBuilder sb = new StringBuilder();
        sb.append(__asLN[rng.nextInt(__asLN.length)]);
        sb.append(" ");
        sb.append(__asFN[rng.nextInt(__asFN.length)]);
        return sb.toString();
    }

    public String getAddress() {
        StringBuilder sb = new StringBuilder();
        int j = rng.nextInt(30000) + 1;
        sb.append("" + j);
        sb.append(", ");
        j = rng.nextInt(100) + 1;
        sb.append("" + j);
        sb.append(" ");
        sb.append(__asStreetType[rng.nextInt(__asStreetType.length)]);
        sb.append(',');
        sb.append(__asCityState[rng.nextInt(__asCityState.length)]);
        return sb.toString();

    }
    private static String[] __asStreetType = {
        "Road",
        "Avenue",
        "Boulevard",
        "Way",
        "Street",
        "Hill"
    };

    private static String[] __asLN = {
        "SMITH",
        "JOHNSON",
        "WILLIAMS",
        "BROWN",
        "JONES",
        "MILLER",
        "DAVIS",
        "GARCIA",
        "RODRIGUEZ",
        "WILSON",
        "MARTINEZ",
        "ANDERSON",
        "TAYLOR",
        "THOMAS",
        "HERNANDEZ",
        "MOORE",
        "MARTIN",
        "JACKSON",
        "THOMPSON",
        "WHITE",
        "LOPEZ",
        "LEE",
        "GONZALEZ",
        "HARRIS",
        "CLARK",
        "LEWIS",
        "ROBINSON",
        "WALKER",
        "PEREZ",
        "HALL",
        "YOUNG",
        "ALLEN",
        "SANCHEZ",
        "WRIGHT",
        "KING",
        "SCOTT",
        "GREEN",
        "BAKER",
        "ADAMS",
        "NELSON",
        "HILL",
        "RAMIREZ",
        "CAMPBELL",
        "MITCHELL",
        "ROBERTS",
        "CARTER",
        "PHILLIPS",
        "EVANS",
        "TURNER",
        "TORRES",
        "PARKER",
        "COLLINS",
        "EDWARDS",
        "STEWART",
        "FLORES",
        "MORRIS",
        "NGUYEN",
        "MURPHY",
        "RIVERA",
        "COOK",
        "ROGERS",
        "MORGAN",
        "PETERSON",
        "COOPER",
        "REED",
        "BAILEY",
        "BELL",
        "GOMEZ",
        "KELLY",
        "HOWARD",
        "WARD",
        "COX",
        "DIAZ",
        "RICHARDSON",
        "WOOD",
        "WATSON",
        "BROOKS",
        "BENNETT",
        "GRAY",
        "JAMES",
        "REYES",
        "CRUZ",
        "HUGHES",
        "PRICE",
        "MYERS",
        "LONG",
        "FOSTER",
        "SANDERS",
        "ROSS",
        "MORALES",
        "POWELL",
        "SULLIVAN",
        "RUSSELL",
        "ORTIZ",
        "JENKINS",
        "GUTIERREZ",
        "PERRY",
        "BUTLER",
        "BARNES",
        "FISHER",
        "HENDERSON",
        "COLEMAN",
        "SIMMONS",
        "PATTERSON",
        "JORDAN",
        "REYNOLDS",
        "HAMILTON",
        "GRAHAM",
        "KIM",
        "GONZALES",
        "ALEXANDER",
        "RAMOS",
        "WALLACE",
        "GRIFFIN",
        "WEST",
        "COLE",
        "HAYES",
        "CHAVEZ",
        "GIBSON",
        "BRYANT",
        "ELLIS",
        "STEVENS",
        "MURRAY",
        "FORD",
        "MARSHALL",
        "OWENS",
        "MCDONALD",
        "HARRISON",
        "RUIZ",
        "KENNEDY",
        "WELLS",
        "ALVAREZ",
        "WOODS",
        "MENDOZA",
        "CASTILLO",
        "OLSON",
        "WEBB",
        "WASHINGTON",
        "TUCKER",
        "FREEMAN",
        "BURNS",
        "HENRY",
        "VASQUEZ",
        "SNYDER",
        "SIMPS",};
    private static String[] __asFN = {
        "Michael",
        "Christopher",
        "Jessica",
        "Matthew",
        "Ashley",
        "Jennifer",
        "Joshua",
        "Amanda",
        "Daniel",
        "David",
        "James",
        "Robert",
        "John",
        "Joseph",
        "Andrew",
        "Ryan",
        "Brandon",
        "Jason",
        "Justin",
        "Sarah",
        "William",
        "Jonathan",
        "Stephanie",
        "Brian",
        "Nicole",
        "Nicholas",
        "Anthony",
        "Heather",
        "Eric",
        "Elizabeth",
        "Adam",
        "Megan",
        "Melissa",
        "Kevin",
        "Steven",
        "Thomas",
        "Timothy",
        "Christina",
        "Kyle",
        "Rachel",
        "Laura",
        "Lauren",
        "Amber",
        "Brittany",
        "Danielle",
        "Richard",
        "Kimberly",
        "Jeffrey",
        "Amy",
        "Crystal",
        "Michelle",
        "Tiffany",
        "Jeremy",
        "Benjamin",
        "Mark",
        "Emily",
        "Aaron",
        "Charles",
        "Rebecca",
        "Jacob",
        "Stephen",
        "Patrick",
        "Sean",
        "Erin",
        "Zachary",
        "Jamie",
        "Kelly",
        "Samantha",
        "Nathan",
        "Sara",
        "Dustin",
        "Paul",
        "Angela",
        "Tyler",
        "Scott",
        "Katherine",
        "Andrea",
        "Gregory",
        "Erica",
        "Mary",
        "Travis",
        "Lisa",
        "Kenneth",
        "Bryan",
        "Lindsey",
        "Kristen",
        "Jose",
        "Alexander",
        "Jesse",
        "Katie",
        "Lindsay",
        "Shannon",
        "Vanessa",
        "Courtney",
        "Christine",
        "Alicia",
        "Cody",
        "Allison",
        "Bradley",
        "Samuel",
        "Shawn",
        "April",
        "Derek",
        "Kathryn",
        "Kristin",
        "Chad",
        "Jenna",
        "Tara",
        "Maria",
        "Krystal",
        "Jared",
        "Anna",
        "Edward",
        "Julie",
        "Peter",
        "Holly",
        "Marcus",
        "Kristina",
        "Natalie",
        "Jordan",
        "Victoria",
        "Jacqueline",
        "Corey",
        "Keith",
        "Monica",
        "Juan",
        "Donald",
        "Cassandra",
        "Meghan",
        "Joel",
        "Shane",
        "Phillip",
        "Patricia",
        "Brett",
        "Ronald",
        "Catherine",
        "George",
        "Antonio",
        "Cynthia",
        "Stacy",
        "Kathleen",
        "Raymond",
        "Carlos",
        "Brandi",
        "Douglas",
        "Nathaniel",
        "Ian",
        "Craig",
        "Brandy",
        "Alex",
        "Valerie",
        "Veronica",
        "Cory",
        "Whitney",
        "Gary",
        "Derrick",
        "Philip",
        "Luis",
        "Diana",
        "Chelsea",
        "Leslie",
        "Caitlin",
        "Leah",
        "Natasha",
        "Erika",
        "Casey",
        "Latoya",
        "Erik",
        "Dana",
        "Victor",
        "Brent",
        "Dominique",
        "Frank",
        "Brittney",
        "Evan",
        "Gabriel",
        "Julia",
        "Candice",
        "Karen",
        "Melanie",
        "Adrian",
        "Stacey",
        "Margaret",
        "Sheena",
        "Wesley",
        "Vincent",
        "Alexandra",
        "Katrina",
        "Bethany",
        "Nichole",
        "Larry",
        "Jeffery",
        "Curtis",
        "Carrie",
        "Todd",
        "Blake",
        "Christian",
        "Randy",
        "Dennis",
        "Alison",
        "Trevor",
        "Seth",
        "Kara",
        "Joanna",
        "Rachael",
        "Luke",
        "Felicia",
        "Brooke",
        "Austin",
        "Candace",
        "Jasmine",
        "Jesus",
        "Alan",
        "Susan",
        "Sandra",
        "Tracy",
        "Kayla",
        "Nancy",
        "Tina",
        "Krystle",
        "Russell",
        "Jeremiah",
        "Carl",
        "Miguel",
        "Tony",
        "Alexis",
        "Gina",
        "Jillian",
        "Pamela",
        "Mitchell",
        "Hannah",
        "Renee",
        "Denise",
        "Molly",
        "Jerry",
        "Misty",
        "Mario",
        "Johnathan",
        "Jaclyn",
        "Brenda",
        "Terry",
        "Lacey",
        "Shaun",
        "Devin",
        "Heidi",
        "Troy",
        "Lucas",
        "Desiree",
        "Jorge",
        "Andre",
        "Morgan",
        "Drew",
        "Sabrina",
        "Miranda",
        "Alyssa",
        "Alisha",
        "Teresa",
        "Johnny",
        "Meagan",
        "Allen",
        "Krista",
        "Marc",
        "Tabitha",
        "Lance",
        "Ricardo",
        "Martin",
        "Chase",
        "Theresa",
        "Melinda",
        "Monique",
        "Tanya",
        "Linda",
        "Kristopher",
        "Bobby",
        "Caleb",
        "Ashlee",
        "Kelli",
        "Henry",
        "Garrett",
        "Mallory",
        "Jill",
        "Jonathon",
        "Kristy",
        "Anne",
        "Francisco",
        "Danny",
        "Robin",
        "Lee",
        "Tamara",
        "Manuel",
        "Meredith",
        "Colleen",
        "Lawrence",
        "Christy",
        "Ricky",
        "Randall",
        "Marissa",
        "Ross",
        "Mathew",
        "Jimmy",
        "Abigail",
        "Kendra",
        "Carolyn",
        "Billy",
        "Deanna",
        "Jenny",
        "Jon",
        "Albert",
        "Taylor",
        "Lori",
        "Rebekah",
        "Cameron",
        "Ebony",
        "Wendy",
        "Angel",
        "Micheal",
        "Kristi",
        "Caroline",
        "Colin",
        "Dawn",
        "Kari",
        "Clayton",
        "Arthur",
        "Roger",
        "Roberto",
        "Priscilla",
        "Darren",
        "Kelsey",
        "Clinton",
        "Walter",
        "Louis",
        "Barbara",
        "Isaac",
        "Cassie",
        "Grant",
        "Cristina",
        "Tonya",
        "Rodney",
        "Bridget",
        "Joe",
        "Cindy",
        "Oscar",
        "Willie",
        "Maurice",
        "Jaime",
        "Angelica",
        "Sharon",
        "Julian",
        "Jack",
        "Jay",
        "Calvin",
        "Marie",
        "Hector",
        "Kate",
        "Adrienne",
        "Tasha",
        "Michele",
        "Ana",
        "Stefanie",
        "Cara",
        "Alejandro",
        "Ruben",
        "Gerald",
        "Audrey",
        "Kristine",
        "Ann",
        "Shana",
        "Javier",
        "Katelyn",
        "Brianna",
        "Bruce",
        "Deborah",
        "Claudia",
        "Carla",
        "Wayne",
        "Roy",
        "Virginia",
        "Haley",
        "Brendan",
        "Janelle",
        "Jacquelyn",
        "Beth",
        "Edwin",
        "Dylan",
        "Dominic",
        "Latasha",
        "Darrell",
        "Geoffrey",
        "Savannah",
        "Reginald",
        "Carly",
        "Fernando",
        "Ashleigh",
        "Aimee",
        "Regina",
        "Mandy",
        "Sergio",
        "Rafael",
        "Pedro",
        "Janet",
        "Kaitlin",
        "Frederick",
        "Cheryl",
        "Autumn",
        "Tyrone",
        "Martha",
        "Omar",
        "Lydia",
        "Jerome",
        "Theodore",
        "Abby",
        "Neil",
        "Shawna",
        "Sierra",
        "Nina",
        "Tammy",
        "Nikki",
        "Terrance",
        "Donna",
        "Claire",
        "Cole",
        "Trisha",
        "Bonnie",
        "Diane",
        "Summer",
        "Carmen",
        "Mayra",
        "Jermaine",
        "Eddie",
        "Micah",
        "Marvin",
        "Levi",
        "Emmanuel",
        "Brad",
        "Taryn",
        "Toni",
        "Jessie",
        "Evelyn",
        "Darryl",
        "Ronnie",
        "Joy",
        "Adriana",
        "Ruth",
        "Mindy",
        "Spencer",
        "Noah",
        "Raul",
        "Suzanne",
        "Sophia",
        "Dale",
        "Jodi",
        "Christie",
        "Raquel",
        "Naomi",
        "Kellie",
        "Ernest",
        "Jake",
        "Grace",
        "Tristan",
        "Shanna",
        "Hilary",
        "Eduardo",
        "Ivan",
        "Hillary",
        "Yolanda",
        "Alberto",
        "Andres",
        "Olivia",
        "Armando",
        "Paula",
        "Amelia",
        "Sheila",
        "Rosa",
        "Robyn",
        "Kurt",
        "Dane",
        "Glenn",
        "Nicolas",
        "Gloria",
        "Eugene",
        "Logan",
        "Steve",
        "Ramon",
        "Bryce",
        "Tommy",
        "Preston",
        "Keri",
        "Devon",
        "Alana",
        "Marisa",
        "Melody",
        "Rose",
        "Barry",
        "Marco",
        "Karl",
        "Daisy",
        "Leonard",
        "Randi",
        "Maggie",
        "Charlotte",
        "Emma",
        "Terrence",
        "Justine",
        "Britney",
        "Lacy",
        "Jeanette",
        "Francis",
        "Tyson",
        "Elise",
        "Sylvia",
        "Rachelle",
        "Stanley",
        "Debra",
        "Brady",
        "Charity",
        "Hope",
        "Melvin",
        "Johanna",
        "Karla",
        "Jarrod",
        "Charlene",
        "Gabrielle",
        "Cesar",
        "Clifford",
        "Byron",
        "Terrell",
        "Sonia",
        "Julio",
        "Stacie",
        "Shelby",
        "Shelly",
        "Edgar",
        "Roxanne",
        "Dwayne",
        "Kaitlyn",
        "Kasey",
        "Jocelyn",
        "Alexandria",
        "Harold",
        "Esther",
        "Kerri",
        "Ellen",
        "Abraham",
        "Cedric",
        "Carol",
        "Katharine",
        "Shauna",
        "Frances",
        "Antoine",
        "Tabatha",
        "Annie",
        "Erick",
        "Alissa",
        "Sherry",
        "Chelsey",
        "Franklin",
        "Branden",
        "Helen",
        "Traci",
        "Lorenzo",
        "Dean",
        "Sonya",
        "Briana",
        "Angelina",
        "Trista",
        "Bianca",
        "Leticia",
        "Tia",
        "Kristie",
        "Stuart",
        "Laurie",
        "Harry",
        "Leigh",
        "Elisabeth",
        "Alfredo",
        "Aubrey",
        "Ray",
        "Arturo",
        "Joey",
        "Kelley",
        "Max",
        "Andy",
        "Latisha",
        "Johnathon",
        "India",
        "Eva",
        "Ralph",
        "Yvonne",
        "Warren",
        "Kirsten",
        "Miriam",
        "Kelvin",
        "Lorena",
        "Staci",
        "Anita",
        "Rene",
        "Cortney",
        "Orlando",
        "Carissa",
        "Jade"
    };
    private static String[] __asCityState = {
        "New York, NY",
        "Los Angeles, CA",
        "Chicago, IL",
        "Miami, FL",
        "Dallas, TX",
        "Philadelphia, PA",
        "Houston, TX",
        "Atlanta, GA",
        "Washington, DC",
        "Boston, MA",
        "Phoenix, AZ",
        "Seattle, WA",
        "San Francisco, CA",
        "Detroit, MI",
        "San Diego, CA",
        "Minneapolis, MN",
        "Tampa, FL",
        "Denver, CO",
        "Brooklyn, NY",
        "Queens, NY",
        "Riverside, CA",
        "Baltimore, MD",
        "Las Vegas, NV",
        "Portland, OR",
        "San Antonio, TX",
        "St. Louis, MO",
        "Sacramento, CA",
        "Orlando, FL",
        "San Jose, CA",
        "Cleveland, OH",
        "Pittsburgh, PA",
        "Austin, TX",
        "Cincinnati, OH",
        "Kansas City, MO",
        "Manhattan, NY",
        "Indianapolis, IN",
        "Columbus, OH",
        "Charlotte, NC",
        "Virginia Beach, VA",
        "Bronx, NY",
        "Milwaukee, WI",
        "Providence, RI",
        "Jacksonville, FL",
        "Salt Lake City, UT",
        "Nashville, TN",
        "Richmond, VA",
        "Memphis, TN",
        "Raleigh, NC",
        "New Orleans, LA",
        "Louisville, KY",
        "Oklahoma City, OK",
        "Bridgeport, CT",
        "Buffalo, NY",
        "Fort Worth, TX",
        "Hartford, CT",
        "Tucson, AZ",
        "Omaha, NE",
        "El Paso, TX",
        "Honolulu, HI",
        "McAllen, TX",
        "Albuquerque, NM",
        "Birmingham, AL",
        "Sarasota, FL",
        "Dayton, OH",
        "Rochester, NY",
        "Fresno, CA",
        "Allentown, PA",
        "Tulsa, OK",
        "Cape Coral, FL",
        "Concord, CA",
        "Colorado Springs, CO",
        "Charleston, SC",
        "Springfield, MA",
        "Grand Rapids, MI",
        "Mission Viejo, CA",
        "Albany, NY",
        "Knoxville, TN",
        "Bakersfield, CA",
        "Ogden, UT",
        "Baton Rouge, LA",
        "Akron, OH",
        "New Haven, CT",
        "Columbia, SC",
        "Mesa, AZ",
        "Palm Bay, FL",
        "Provo, UT",
        "Worcester, MA",
        "Murrieta, CA",
        "Greenville, SC",
        "Wichita, KS",
        "Toledo, OH",
        "Staten Island, NY",
        "Des Moines, IA",
        "Long Beach, CA",
        "Port St. Lucie, FL",
        "Denton, TX",
        "Madison, WI",
        "Reno, NV",
        "Harrisburg, PA",
        "Little Rock, AR",
        "Oakland, CA",
        "Durham, NC",
        "Winston-Salem, NC",
        "Bonita Springs, FL",
        "Indio, CA",
        "Palm Coast, FL",
        "Chattanooga, TN",
        "Spokane, WA",
        "Syracuse, NY",
        "Lancaster, PA",
        "Arlington, TX",
        "Stockton, CA",
        "Poughkeepsie, NY",
        "Augusta, GA",
        "Boise, ID",
        "Oxnard, CA",
        "Scranton, PA",
        "Modesto, CA",
        "Kissimmee, FL",
        "Aurora, CO",
        "Youngstown, OH",
        "Fayetteville, AR",
        "Anaheim, CA",
        "Pensacola, FL",
        "Victorville, CA",
        "Lancaster, CA",
        "Greensboro, NC",
        "Corpus Christi, TX",
        "Fort Wayne, IN",
        "Santa Ana, CA",
        "Flint, MI",
        "Fayetteville, NC",
        "Jackson, MS",
        "Santa Rosa, CA",
        "Lansing, MI",
        "San Juan, PR",
        "Lexington, KY",
        "Ann Arbor, MI",
        "Henderson, NV",
        "Huntsville, AL",
        "Mobile, AL",
        "Fort Collins, CO",
        "Asheville, NC",
        "Santa Clarita, CA",
        "St. Paul, MN",
        "Antioch, CA",
        "Lakeland, FL",
        "Trenton, NJ",
        "Lincoln, NE",
        "Springfield, MO",
        "Anchorage, AK",
        "Plano, TX",
        "Irvine, CA",
        "Davenport, IA",
        "Rockford, IL",
        "Newark, NJ",
        "South Bend, IN",
        "Shreveport, LA",
        "Round Lake Beach, IL",
        "Savannah, GA",
        "Myrtle Beach, SC",
        "Chula Vista, CA",
        "Eugene, OR",
        "Canton, OH",
        "Lubbock, TX",
        "Reading, PA",
        "Winter Haven, FL",
        "Salem, OR",
        "St. Petersburg, FL",
        "Lafayette, LA",
        "Laredo, TX",
        "Jersey City, NJ",
        "Concord, NC",
        "Columbus, GA",
        "Chandler, AZ",
        "McKinney, TX",
        "Scottsdale, AZ",
        "Killeen, TX",
        "Tallahassee, FL",
        "Peoria, IL",
        "Wilmington, NC",
        "Montgomery, AL",
        "Gilbert, AZ",
        "Glendale, AZ",
        "North Las Vegas, NV",
        "Chesapeake, VA",
        "Barnstable, MA",
        "Norfolk, VA",
        "Fremont, CA",
        "Kennewick, WA",
        "Garland, TX",
        "Irving, TX",
        "Visalia, CA",
        "Atlantic City, NJ",
        "Paradise, NV",
        "Nashua, NH",
        "Arlington, VA",
        "Hialeah, FL",
        "York, PA",
        "Evansville, IN",
        "Avondale, AZ",
        "Brownsville, TX",
        "Gulfport, MS",
        "Appleton, WI",
        "Bremerton, WA",
        "Hickory, NC",
        "Tacoma, WA",
        "San Bernardino, CA",
        "College Station, TX",
        "Kalamazoo, MI",
        "Thousand Oaks, CA",
        "Roanoke, VA",
        "Fontana, CA",
        "Moreno Valley, CA",
        "North Port, FL",
        "Fargo, ND",
        "Green Bay, WI",
        "Spring Valley, NV",
        "Amarillo, TX",
        "Portland, ME",
        "Santa Barbara, CA",
        "Gainesville, FL",
        "Olympia, WA",
        "Frisco, TX",
        "Yonkers, NY",
        "Norwich, CT",
        "Glendale, CA",
        "Huntington Beach, CA",
        "Deltona, FL",
        "Aurora, IL",
        "Tempe, AZ",
        "Overland Park, KS",
        "Grand Prairie, TX",
        "Sunrise Manor, NV",
        "Waco, TX",
        "Salinas, CA",
        "Waterbury, CT",
        "Clarksville, TN",
        "Cedar Rapids, IA",
        "Sioux Falls, SD",
        "Huntington, WV",
        "Ontario, CA",
        "Hagerstown, MD",
        "Erie, PA",
        "Vancouver, WA",
        "Nampa, ID",
        "Spartanburg, SC",
        "Gastonia, NC",
        "Fort Lauderdale, FL",
        "Lorain, OH",
        "Murfreesboro, TN",
        "High Point, NC",
        "Newport News, VA",
        "Rancho Cucamonga, CA",
        "Hemet, CA",
        "Santa Cruz, CA",
        "Danbury, CT",
        "Peoria, AZ",
        "Oceanside, CA",
        "Elk Grove, CA",
        "Pembroke Pines, FL",
        "Vallejo, CA",
        "Garden Grove, CA",
        "Enterprise, NV",
        "Medford, OR",
        "Cary, NC",
        "Marysville, WA",
        "Corona, CA",
        "Ocala, FL",
        "Fredericksburg, VA",
        "Gainesville, GA",
        "Manchester, NH",
        "Bayamon, PR",
        "Champaign, IL",
        "Alexandria, VA",
        "Hayward, CA",
        "Springfield, IL",
        "Lakewood, CO",
        "Lafayette, IN",
        "Frederick, MD",
        "Lake Charles, LA",
        "Odessa, TX",
        "Tuscaloosa, AL",
        "Warner Robins, GA",
        "Palmdale, CA",
        "Hollywood, FL",
        "Midland, TX",
        "Leesburg, FL",
        "Port Arthur, TX",
        "Muskegon, MI",
        "Macon, GA",
        "Kansas City, KS",
        "Sunnyvale, CA",
        "Pomona, CA",
        "Escondido, CA",
        "Pasadena, TX",
        "New Bedford, MA",
        "Fairfield, CA",
        "Naperville, IL",
        "Bellevue, WA",};
}
